### ISSUE TITLE
web design

### ISSUE THREAD

**Issue by wearecodexx** [wearecodexx/crypto-gamehub#10]
- Header
- Game
- Footer with credits
- Link to main collaborators social media and wallets

This is probably going to be used as base for all the games.

**Comment by fabiyamada** [comment]
Preview:

![single game site editable](https://user-images.githubusercontent.com/33674731/39800788-426b8294-5326-11e8-8806-bdcd9a75d0f3.png)

[GOOGLE DRIVE FOLDER](https://drive.google.com/open?id=1growQg-6-8gDpYDNizYAjGhKQLhU-kWa) Find PSD, PDF, and image files.
