### ISSUE TITLE
New Background Game 

### ISSUE THREAD

**Issue by karmachela** [wearecodexx/crypto-gamehub#11]
Hello, I love the new game you created, SPAMPIG is very simple but very exciting and addictive. I think the game will be more fun if supported by the right atmosphere, in this case the use of the background will be very helpful.

For that I have created a background as we discussed through discord.

![spampig_background_full](https://user-images.githubusercontent.com/37863762/39858323-6a9fe1b6-5460-11e8-90c9-59a0a510baee.png)

**Comment by wearecodexx** [comment]
It is amazing! thank you so much for your work! We will use this ASAP!
